### ISSUE TITLE
About performance

### ISSUE THREAD

**Issue by gaomenghao-nb** [nnzzll/scn#1]
Hello, how does this implementation compare with the performance of the official version?

**Comment by nnzzll** [comment]
Here are several metrics compared with official version.


|      | this(test 1 set) | official(test 1 set) | this(test 2 set) | official (test 2 set) |
| :--- | :--------------: | :------------------: | :--------------: | :-------------------: |
| ID   |      98.15%      |        95.65%        |      97.66%      |        94.25%         |
| Dice |      94.54%      |        90.9%         |      95.11%      |         89.8%         |
| PE   |      3.43mm      |        4.27mm        |       2.89       |        4.80mm         |

**Comment by gaomenghao-nb** [comment]
Good job!! Thank you very much!
